# Generated by Django 3.2.7 on 2021-12-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.CharField(max_length=64)),
                ('ename', models.IntegerField()),
                ('esal', models.IntegerField()),
                ('eaddr', models.CharField(max_length=64)),
            ],
        ),
    ]
